var trades = [
  {
    condition: "New",
    tradeId: "918d2h",
    title: "A Game of Thrones",
    genre: "Fantasy",
    by: "Joaquim Barreiros",
    location: "Algarve",
    returnBook: "Yes",
    bookByBook: "Book by Book",
    additional: "Got it and never read it.",
    image: "../assets/gameOf.jpg"
  },
  {
    condition: "Used",
    tradeId: "900d2h",
    title: "Lord of The Rings",
    genre: "Fantasy",
    by: "Carlos Notas",
    location: "Almada",
    returnBook: "No",
    bookByBook: "Book by Book",
    additional: "Read the book once, but it's in good condition, only a few dents.",
    image: "../assets/lotr.jpg"
  },
  {
    condition: "Old",
    tradeId: "236dee",
    title: "A Game of Thrones",
    genre: "Fantasy",
    by: "Carlos Notas",
    location: "Almada",
    returnBook: "Yes",
    bookByBook: "Book by Book",
    additional: "Old book that belonged to my mom.",
    image: "../assets/gameOf.jpg"
  },
  {
    condition: "New",
    tradeId: "h37o2h",
    title: "Harry Potter",
    genre: "Fantasy",
    by: "Joaquim Barreiros",
    location: "Caparica",
    returnBook: "No",
    bookByBook: "Book by Book",
    additional: "Got it and never read it.",
    image: "../assets/book_placerholder.jpeg"
  },
  {
    condition: "Used",
    tradeId: "83jdh",
    title: "Harry Potter",
    genre: "Fantasy",
    by: "Carlos Notas",
    location: "Almada",
    returnBook: "No",
    bookByBook: "Book by Book",
    additional: "Read the book once, but it's in good condition, only a few dents.",
    image: "../assets/book_placerholder.jpeg"
  },
  {
    condition: "Old",
    tradeId: "23h2id",
    title: "Total Recall",
    genre: "Biography",
    by: "Carlos Notas",
    location: "Almada",
    returnBook: "Yes",
    bookByBook: "Book by Book",
    additional: "Old book that belonged to my mom.",
    image: "../assets/arnold.jpg"
  },
  {
    condition: "New",
    tradeId: "9jdjw2",
    title: "Howard",
    genre: "Horror",
    by: "Joaquim Barreiros",
    location: "Lisboa",
    returnBook: "No",
    bookByBook: "Book by Book",
    additional: "Got it and never read it.",
    image: "../assets/book_placerholder.jpeg"
  },
  {
    condition: "Used",
    tradeId: "87ftf2",
    title: "Lord of The Rings",
    genre: "Fantasy",
    by: "Carlos Notas",
    location: "Almada",
    returnBook: "No",
    bookByBook: "Book by Book",
    additional: "Read the book once, but it's in good condition, only a few dents.",
    image: "../assets/lotr.jpg"
  },
  {
    condition: "Old",
    tradeId: "cn3232",
    title: "Lord of The Rings",
    genre: "Fantasy",
    by: "Carlos Notas",
    location: "Almada",
    returnBook: "Yes",
    bookByBook: "Book by Book",
    additional: "Old book that belonged to my mom.",
    image: "../assets/lotr.jpg"
  },
  {
    condition: "New",
    tradeId: "238f73",
    title: "A Game of Thrones",
    genre: "Fantasy",
    by: "Joaquim Barreiros",
    location: "Almada",
    returnBook: "No",
    bookByBook: "Book by Book",
    additional: "Got it and never read it.",
    image: "../assets/gameOf.jpg"
  },
  {
    condition: "Used",
    tradeId: "dj9832",
    title: "Harry Potter",
    genre: "Fantasy",
    by: "Carlos Notas",
    location: "Almada",
    returnBook: "No",
    bookByBook: "Book by Book",
    additional: "Read the book once, but it's in good condition, only a few dents.",
    image: "../assets/book_placerholder.jpeg"
  }

];